language: python

python:
- 3.9
services:
  - postgresql
addons:
  postgresql: '13'
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PGPORT=5433
    - PGUSER=travis

install:
- pip install -q pipenv
- pipenv sync --dev
- cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U $PGUSER

script:
- pipenv run flake8
- pipenv run pytest --cov=pypro

branches:
  only:
  - main

after_success:
- pipenv run codecov
