# Generated by Django 4.0.5 on 2022-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='itens',
            field=models.ManyToManyField(blank=True, through='base.ItemMovimentado', to='base.item'),
        ),
    ]
